# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b81ecb8dce976bfc3d0c520aa111a8e16b8cf7b4ac3d9ab261c42dea392b3d4aa2e23745be60da0c09d0fca258e310b55d44ea75b19ab29139400792b4a11ff

test:
  secret_key_base: fdbc7c69206b37c61757e3779a10924c8c616f55eed070ab79eb5d75fecff11e7b3bd9f3f872c9e92ece5bcd2e18b1c947d5e82866d6709a93493bffb6fe9c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
